DROP TABLE IF EXISTS word,
team,
round,
game;

DELETE FROM word;

ROLLBACK;
COMMIT;

CREATE TABLE word (
	word_id SERIAL PRIMARY KEY,
	category VARCHAR(300) NOT NULL,
	word VARCHAR(500) NOT NULL
);

-- ===== INSERT
INSERT INTO word (
	category, word)
VALUES
	('ANIME NAME', 'I WANT TO EAT YOUR PANCREASE IS FAR FROM A HORROR SERIES'),
	('FRUIT', 'MANGOSTEEN'),
	('FRUIT', 'RAMBUTAN'),
	('ANIME NAME', 'ATTACK ON TITAN')


-- ===== QUERYING
SELECT *
FROM "fhm".word
WHERE word = "";


SELECT *
FROM word;